export { default as PublicLayout } from './PublicLayout'
export { default as Home } from './Home'
export { default as AboutUs } from './AboutUs'
export { default as OurAgent } from './OurAgent'
export { default as Properties } from './Properties'
export { default as Search } from './Search'
